
export const AllBanksList: {[key: string]: string} = {
    "ABHY": "Abhyudaya Co-operative Bank",
    "ABNA": "Royal Bank of Scotland N.V.",
    "ADCC": "Akola District Central Co-operative Bank",
    "AHDC": "Ahmednagar District Central Co-operative Bank",
    "AIRP": "Airtel Payments Bank",
    "AJAR": "Ajara Urban Co-operative Bank",
    "AJHC": "Ambarnath Jai-hind Co-operative Bank",
    "AKJB": "Akola Janata Commercial Co-operative Bank",
    "ALLA": "Allahabad Bank",
    "AMCB": "Ahmedabad Mercantile Co-operative Bank",
    "AMDN": "Ahmednagar Merchants Co-operative Bank",
    "ANDB": "Andhra Bank",
    "ANZB": "Australia and New Zealand Banking Group",
    "APBL": "Andhra Pradesh State Co-operative Bank",
    "APGB": "Andhra Pragathi Grameena Bank",
    "APGV": "Andhra Pradesh Grameena Vikas Bank",
    "APMC": "A.P. Mahesh Co-operative Urban Bank",
    "ARBL": "Arvind Sahakari Bank",
    "ASBL": "Apna Sahakari Bank",
    "AUBL": "AU Small Finance Bank",
    "AUCB": "Almora Urban Co-operative Bank",
    "BACB": "Bassein Catholic Co-operative Bank",
    "BARA": "Baramati Sahakari Bank",
    "BARB": "Bank of Baroda",
    "BARC": "Barclays Bank",
    "BBKM": "Bank of Bahrein and Kuwait",
    "BCBM": "Bharat Co-operative Bank",
    "BCEY": "Bank of Ceylon",
    "BDBL": "Bandhan Bank",
    "BKDN": "Dena Bank",
    "BKID": "Bank of India",
    "BMCB": "Bombay Mercantile Co-operative Bank",
    "BNPA": "BNP Paribas Bank",
    "BNSB": "Bhagini Nivedita Sahakari Bank Pune",
    "BOFA": "Bank of America",
    "BOTM": "MUFG Bank",
    "CBIN": "Central Bank of India",
    "CCBL": "Citizen Credit Co-operative Bank",
    "CHAS": "JP Morgan Chase Bank NA",
    "CITI": "CITI Bank",
    "CIUB": "City Union Bank",
    "CLBL": "Capital Small Finance Bank",
    "CNRB": "Canara Bank",
    "COAS": "Coastal Local Area Bank",
    "CORP": "Corporation Bank",
    "COSB": "Cosmos Co-operative Bank",
    "CRES": "Credit Suisse AG",
    "CRGB": "Chhattisgarh Rajya Gramin Bank",
    "CRLY": "Credit Agricole Corporate and Investment Bank",
    "CRUB": "Shri Chhatrapati Rajashri Shahu Urban Co-operative Bank",
    "CSBK": "Catholic Syrian Bank",
    "CSBX": "Chartered Sahakari Bank Niyamitha",
    "CTCB": "Chinatrust Commercial Bank",
    "DBSS": "Development Bank of Singapore",
    "DCBL": "DCB Bank",
    "DCUB": "Darussalam Co-operative Urban Bank",
    "DEOB": "Deogiri Nagari Sahakari Bank Aurangabad",
    "DEUT": "Deutsche Bank",
    "DICG": "Deposit Insurance and Credit Guarantee Corporation",
    "DLSC": "Delhi State Co-operative Bank",
    "DLXB": "Dhanlaxmi Bank",
    "DMKJ": "Dmk Jaoli Bank",
    "DNSB": "Dombivli Nagari Sahakari Bank",
    "DOHB": "Doha Bank QSC",
    "DURG": "Durgapur Steel Peoples Co-operative Bank",
    "EBIL": "Emirates NBD Bank",
    "EIBI": "Export Import Bank of India",
    "ESFB": "Equitas Small Finance Bank",
    "ESMF": "Esaf Small Finance Bank",
    "FDRL": "Federal Bank",
    "FINO": "Fino Payments Bank",
    "FIRN": "Firstrand Bank",
    "FSFB": "Fincare Small Finance Bank",
    "GBCB": "Greater Bombay Co-operative Bank",
    "GDCB": "Gadchiroli District Central Co-operative Bank",
    "GSCB": "Gujarat State Co-operative Bank",
    "HARC": "Haryana State Co-operative Apex Bank",
    "HCBL": "HASTI Co-operative Bank",
    "HDFC": "HDFC Bank",
    "HPSC": "Himachal Pradesh State Co-operative Bank",
    "HSBC": "Hongkong & Shanghai Banking Corporation",
    "HUSB": "Hutatma Sahakari Bank",
    "HVBK": "Woori Bank",
    "IBBK": "PT Bank Maybank Indonesia TBK",
    "IBKL": "IDBI",
    "IBKO": "Industrial Bank of Korea",
    "ICBK": "Industrial and Commercial Bank of China",
    "ICIC": "ICICI Bank",
    "ICLL": "Indian Clearing Corporation",
    "IDFB": "IDFC FIRST Bank",
    "IDIB": "Indian Bank",
    "IDUK": "Idukki District Co-operative Bank",
    "INDB": "Indusind Bank",
    "IOBA": "Indian Overseas Bank",
    "IPOS": "India Post Payments Bank",
    "ITBL": "Irinjalakuda Town Co-operative Bank",
    "JAKA": "Jammu and Kashmir Bank",
    "JANA": "Janaseva Sahakari Bank, Pune",
    "JASB": "Janaseva Sahakari Bank (Borivli)",
    "JIOP": "Jio Payments Bank",
    "JJSB": "Jalgaon Janata Bank",
    "JPCB": "Jalgaon Peoples Co-operative Bank",
    "JSBL": "Janakalyan Sahakari Bank",
    "JSBP": "Janata Sahakari Bank (Pune)",
    "JSFB": "Jana Small Finance Bank",
    "JTSC": "Janatha Seva Co-operative Bank",
    "KACE": "Kangra Central Co-operative Bank",
    "KAIJ": "Kallappanna Awade Ichalkaranji Janata Sahakari Bank",
    "KANG": "Kangra Co-operative Bank",
    "KARB": "Karnataka Bank",
    "KBKB": "Kookmin Bank",
    "KCCB": "Kalupur Commercial Co-operative Bank",
    "KDCB": "Kozhikode District Co-operative Bank",
    "KJSB": "Kalyan Janata Sahakari Bank",
    "KKBK": "Kotak Mahindra Bank",
    "KLGB": "Kerala Gramin Bank",
    "KNSB": "Kurla Nagarik Sahakari Bank",
    "KOEX": "KEB Hana Bank",
    "KOLH": "Kolhapur Urban Co-operative Bank",
    "KSBK": "Kerala State Co-operative Bank",
    "KSCB": "Karnataka State Co-operative Apex Bank",
    "KUCB": "Karad Urban Co-operative Bank",
    "KVBL": "Karur Vysya Bank",
    "KVGB": "Karnataka Vikas Grameena Bank",
    "LAVB": "Laxmi Vilas Bank",
    "MAHB": "Bank of Maharashtra",
    "MAHG": "Maharashtra Gramin Bank",
    "MCAB": "Meghalaya Co-operative Apex Bank",
    "MCBL": "Mahanagar Co-operative Bank",
    "MDBK": "Model Co-operative Bank",
    "MDCB": "Mumbai District Central Co-operative Bank",
    "MHCB": "Mizuho Bank",
    "MKPB": "Malkapur Urban Co-operative Bank",
    "MSBL": "Malad Sahakari Bank",
    "MSCI": "Maharashtra State Co-operative Bank",
    "MSHQ": "Mashreq Bank",
    "MSLM": "Muslim Co-operative Bank",
    "MSNU": "Mehsana Urban Co-operative Bank",
    "MUBL": "Municipal Co-operative Bank",
    "MVCB": "Sir M Visvesvaraya Co-operative Bank",
    "NBAD": "National Bank of Abu Dhabi PJSC",
    "NBRD": "National Bank for Agriculture and Development",
    "NCUB": "Nilambur Co-operative Urban Bank",
    "NESF": "North East Small Finance Bank",
    "NGSB": "Nagpur Nagarik Sahakari Bank",
    "NICB": "New India Co-operative Bank",
    "NJBK": "Nav Jeevan Co-operative Bank",
    "NKGS": "NKGSB Co-operative Bank",
    "NMCB": "Nasik Merchants Co-operative Bank",
    "NNSB": "Nutan Nagarik Sahakari Bank",
    "NOSC": "Bank of Nova Scotia",
    "NSPB": "NSDL Payments Bank",
    "NTBL": "Nainital Bank",
    "NUCB": "Nagar Urban Co-operative Bank",
    "NVNM": "Navnirman Co-operative Bank",
    "ORBC": "Oriental Bank of Commerce",
    "ORCB": "Odisha State Co-operative Bank",
    "PJSB": "Gopinath Patil Parsik Janata Sahakari Bank",
    "PKGB": "Karnataka Gramin Bank",
    "PMEC": "Prime Co-operative Bank",
    "PSBL": "Pavana Sahakari Bank",
    "PSIB": "Punjab & Sind Bank",
    "PUCB": "Pandharpur Urban Co-operative Bank",
    "PUNB": "Punjab National Bank",
    "PUSD": "Pusad Urban Co-operative Bank",
    "PYTM": "Paytm Payments Bank",
    "QNBA": "Qatar National Bank",
    "RABO": "Rabobank International",
    "RATN": "RBL Bank",
    "RBIN": "Reserve Bank Of India",
    "RBIP": "Reserve Bank of India",
    "RBIS": "Reserve Bank of India",
    "RDCB": "Rajnandgaon District Central Co-operative Bank",
    "RMGB": "Rajasthan Marudhara Gramin Bank",
    "RNSB": "Rajkot Nagarik Sahakari Bank",
    "RRBP": "Rajarambapu Sahakari Bank",
    "RSBL": "Rajgurunagar Sahakari Bank",
    "RSCB": "Rajasthan State Co-operative Bank",
    "RSSB": "Rajarshi Shahu Sahakari Bank",
    "SABR": "SBER Bank",
    "SAHE": "Sahebrao Deshmukh Co-operative Bank",
    "SANT": "Sant Sopankaka Sahakari Bank",
    "SBIN": "State Bank of India",
    "SBLS": "Samarth Sahakari Bank",
    "SCBL": "Standard Chartered Bank",
    "SDCB": "Surat District Co-operative Bank",
    "SDCE": "Satara District Central Co-operative Bank",
    "SECB": "Sree Charan Souhardha Co-operative Bank",
    "SHBK": "Shinhan Bank",
    "SIBL": "South Indian Bank",
    "SIDC": "Sindhudurg District Central Co-operative Bank",
    "SJSB": "Solapur Janata Sahakari Bank",
    "SKNB": "Shree Kadi Nagarik Sahakari Bank",
    "SKSB": "Shikshak Sahakari Bank",
    "SMBC": "Sumitomo Mitsui Banking Corporation",
    "SMCB": "Shivalik Small Finance Bank",
    "SMNB": "Smriti Nagrik Sahakari Bank",
    "SNBK": "Saraspur Nagrik Co-operative Bank",
    "SOGE": "Societe Generale",
    "SPCB": "Surat People's Co-operative Bank",
    "SRCB": "Saraswat Co-operative Bank",
    "STCB": "SBM Bank",
    "SUNB": "Surat National Co-operative Bank",
    "SURY": "Suryoday Small Finance Bank",
    "SUSB": "Suco Souharda Sahakari Bank",
    "SUTB": "Sutex Co-operative Bank",
    "SVCB": "SVC Co-operative Bank",
    "SVSH": "Shree Veershaiv Co-operative Bank",
    "SYNB": "Syndicate Bank",
    "TAUB": "Ankola Urban Co-operative Bank",
    "TBMC": "Banaskantha Mercantile Co-operative Bank",
    "TBSB": "Thane Bharat Sahakari Bank",
    "TDCB": "Thane District Central Co-operative Bank",
    "TGMB": "Tumkur Grain Merchant's Co-operative Bank",
    "THRS": "Thrissur District Co-operative Bank",
    "TJSB": "TJSB Sahakari Bank",
    "TMBL": "Tamilnad Mercantile Bank",
    "TMSB": "The Malad Sahakari Bank",
    "TNCB": "Nawanagar Co-operative Bank",
    "TNSC": "Tamilnadu State Apex Co-operative Bank",
    "TPSC": "Punjab State Co-operative Bank",
    "TSAB": "Telangana State Co-operative Apex Bank",
    "TSSB": "Satara Sahakari Bank",
    "TTCB": "Textile Traders Co-operative Bank",
    "UBIN": "Union Bank of India",
    "UCBA": "UCO Bank",
    "UJVN": "Ujjivan Small Finance Bank",
    "UOVB": "United Overseas Bank",
    "UPCB": "Uttar Pradesh Co-operative Bank",
    "URBN": "Urban Co-operative Bank Perinthalmanna",
    "UTBI": "United Bank of India",
    "UTIB": "Axis Bank",
    "UTKS": "Utkarsh Small Finance Bank",
    "UUCB": "Udaipur Urban Co-operative Bank",
    "VARA": "Varachha Co-operative Bank",
    "VASJ": "Vasai Janata Sahakari Bank",
    "VCOB": "The Vijay Co-operative Bank",
    "VIJB": "Vijaya Bank",
    "VSBL": "Vishweshwar Sahakari Bank",
    "VVSB": "Vasai Vikas Sahakari Bank",
    "WBSC": "West Bengal State Co-operative Bank",
    "YESB": "Yes Bank",
    "ZCBL": "Zoroastrian Co-operative Bank",
    "ZSBL": "Zila Sahakari Bank Ghaziabad",
}
